lichess_toggle_sound:
    pattern:        /toggle-sound
    defaults:       { _controller: LichessBundle:Main:toggleSound }
    requirements:   { _method: POST }
lichess_board_color:
    pattern:        /board-color
    defaults:       { _controller: LichessBundle:Main:boardColor }
    requirements:   { _method: POST }
lichess_wait_friend:
    pattern:        /friend/{id}
    defaults:       { _controller: LichessBundle:Player:waitFriend }
    requirements:   { id: "[\w\-]{12}" }
lichess_cancel_friend:
    pattern:        /friend/{id}/cancel
    defaults:       { _controller: LichessBundle:Player:cancelFriend }
    requirements:   { id: "[\w\-]{12}" }
lichess_game:
    pattern:        /{id}/{color}
    defaults:       { _controller: LichessBundle:Game:show, color: white }
    requirements:   { id: "[\w\-]{8}", color: (white|black) }
lichess_game_stats:
    pattern:        /{id}/stats
    defaults:       { _controller: LichessBundle:Game:stats, color: white }
    requirements:   { id: "[\w\-]{8}" }
lichess_player:
    pattern:        /{id}
    defaults:       { _controller: LichessBundle:Player:show }
    requirements:   { id: "[\w\-]{12}" }
lichess_join_game:
    pattern:        /join/{id}
    defaults:       { _controller: LichessBundle:Game:join }
    requirements:   { id: "[\w\-]{8}" }
lichess_table:
    pattern:        /table/{id}/{color}/{playerFullId}
    defaults:       { _controller: LichessBundle:Player:table, playerFullId "" }
    requirements:   { id: "[\w\-]{8}", color: (white|black), playerFullId: "([\w\-]{12}|)" }
lichess_opponent:
    pattern:        /opponent/{id}/{color}/{playerFullId}
    defaults:       { _controller: LichessBundle:Player:opponent, playerFullId "" }
    requirements:   { id: "[\w\-]{8}", color: (white|black), playerFullId: "([\w\-]{12}|)" }
lichess_list_current:
    pattern:        /games
    defaults:       { _controller: LichessBundle:Game:listCurrent }
lichess_list_current_inner:
    pattern:        /games-refresh/{ids}
    defaults:       { _controller: LichessBundle:Game:listCurrentInner }
lichess_list_all:
    pattern:        /games/all
    defaults:       { _controller: LichessBundle:Game:listAll }
lichess_list_mates:
    pattern:        /games/checkmate
    defaults:       { _controller: LichessBundle:Game:listCheckmate }
lichess_about:
    pattern:        /about
    defaults:       { _controller: LichessBundle:Main:about }
lichess_rematch:
    pattern:        /rematch/{id}
    defaults:       { _controller: LichessBundle:Player:rematch }
    requirements:   { id: "[\w\-]{12}" }
lichess_pgn_viewer:
    pattern:        /analyse/{id}/{color}
    defaults:       { _controller: LichessBundle:Pgn:analyse, color: white }
    requirements:   { id: "[\w\-]{8}", color: (white|black) }
lichess_pgn_export:
    pattern:        /analyse/{id}/export
    defaults:       { _controller: LichessBundle:Pgn:export, color: white }
    requirements:   { id: "[\w\-]{8}" }
lichess_trial_list_unresolved:
    pattern:        /trial/unresolved
    defaults:       { _controller: LichessBundle:Trial:listUnresolved }
lichess_trial_list_guilty:
    pattern:        /trial/guilty
    defaults:       { _controller: LichessBundle:Trial:listGuilty }
lichess_trial_list_innocent:
    pattern:        /trial/innocent
    defaults:       { _controller: LichessBundle:Trial:listInnocent }
lichess_trial_verdict:
    pattern:        /trial/verdict/{id}/{verdict}
    defaults:       { _controller: LichessBundle:Trial:verdict }
lichess_api_new:
    pattern:        /api/game/new
    defaults:       { _controller: LichessBundle:Api:new }
    requirements:   { _method: POST }
lichess_status:
    pattern:        /status
    defaults:       { _controller: LichessBundle:Main:status }
lichess_wiki_index:
    pattern:        /wiki
    defaults:       { _controller: LichessBundle:Wiki:index }
lichess_wiki_show:
    pattern:        /wiki/{slug}
    defaults:       { _controller: LichessBundle:Wiki:show }
