imports:
    - { resource: akismet.yml }
    - { resource: apc.yml }
    - { resource: assetic.yml }
    - { resource: doctrine.yml }
    - { resource: forum.yml }
    - { resource: framework.yml }
    - { resource: lichess.yml }
    - { resource: message.yml }
    - { resource: monolog.yml }
    - { resource: security.yml }
    - { resource: twig.yml }
    - { resource: user.yml }
    - { resource: elastica.yml }
