imports:
    - { resource: config_dev.yml }

web_profiler:
    toolbar: false

framework:
    profiler: false
    test: true

doctrine_mongodb:
    document_managers:
        default:
            metadata_cache_driver: apc
    default_database: lichess_test

lichess:
    test: true
    sync:
        path: ""
        latency: 0
    feature:
        listener: false
