doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
                persist: lichess
    default_database: lichess_%kernel.environment%
    #default_database: lichess
    document_managers:
        default:
            metadata_cache_driver: apc
            auto_mapping: true
