fos_user:
    firewall_name: main
    db_driver: mongodb
    user_class: Application\UserBundle\Document\User
    use_username_form_type: true
    registration:
        confirmation:
            enabled:    false
        form:
            type: lichess_user_registration
    encoder:
        iterations: 1
        encode_as_base64: false
        algorithm: sha1
    service:
        mailer: fos_user.mailer.noop
