framework:
    secret: OUtWsdDDigFl
    charset:       UTF-8
    router: { resource: "%kernel.root_dir%/config/routing.yml" }
    validation: { enable_annotations: true }
    form:            true
    csrf_protection: false
    session:
        default_locale: en
        name:     lichess3
        lifetime: 72000
        auto_start:     true
        domain: .lichess.org
    templating:
        assets_version: 96
        engines: ['twig']
    translator: { fallback: en }
