imports:
    - { resource: ../../config/doctrine.yml }
    - { resource: ../../config/framework.yml }
    - { resource: ../../config/lichess.yml }

# Disable as many features as possible
framework:
    validation: { enabled: false }
    form: false
    session: false
    templating: false

# Define mappings manually
doctrine_mongodb:
    document_managers:
        default:
            auto_mapping: false
            mappings:
                LichessBundle: ~
                LichessOpeningBundle: ~
                LichessUser:
                    type: annotation
                    dir: %kernel.root_dir%/../src/Application/UserBundle/Document
                    prefix: Application\UserBundle\Document
                FOSUser:
                    type: xml
                    dir: %kernel.root_dir%/../vendor/bundles/FOS/UserBundle/Resources/config/doctrine
                    prefix: FOS\UserBundle\Document

# Disable as many features as possible
lichess:
    feature:
        ai: false
        cheat: false
        listener: false
        elo: false
        chess: false
        config: false
        cache: false

# Disable as many features as possible
lichess_opening:
    feature:
        config_persistence: false
        form: false
        starter: false
        cleaner: false
