herzult_forum_index:
    pattern: /
    defaults: { _controller: HerzultForumBundle:Forum:index }

lichess_forum_search:
    pattern: /search
    defaults: { _controller: LichessForumBundle:Search:search }

lichess_forum_newposts:
    pattern: /recent
    defaults: { _controller: LichessForumBundle:Post:recent }
